# Generated by Django 4.0.3 on 2022-07-14 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0002_remove_customuser_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='id',
            field=models.TextField(default='exit', editable=False, verbose_name='UID'),
            preserve_default=False,
        ),
    ]
